
spring:
   rabbitmq:
    host: localhost
   mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyatsharebazar
    password: sharebazar@123
    properties.mail.smtp:
       auth: true
       starttls.enable: true
   zipkin:
     enabled: true
     base-url: http://localhost:9411
     service:
      name: ${spring.application.name}
#========= RabbitMQ configuration ============
  

#============== Eureka client service registration
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
    instance:
     instance-id: ${spring.application.name}:${random.int[5000,6000]}
     prefer-ip-address: true
    #hostname: localhost #ipaddress of this host 
    #secure-port-enabled: false
    #non-secure-port-enabled: true
    #secure-port: ${server.port}
management:
  endpoints:
    web:
      exposure:
        include:
        - "*" #disabling security to enalbe actuator to call actuator/refresh url

server:
  port: 8089


