spring:
  rabbitmq:
    host: rabbitmq
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyatsharebazar
    password: W$%ildl$keH$$L
    properties.mail.smtp:
       auth: true
       starttls.enable: true
   # in docker environment if you don't ignore these network intefaces you won't be able 
   #to hit Eureka ---> your service
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo
  zipkin:
    enabled: true
    base-url: http://zipkin:9411
    service:
      name: ${spring.application.name}
  sleuth:
    sampler:
      probability: 1
#========= RabbitMQ configuration ============
  

#============== Eureka client service registration
eureka:
  client:
    serviceUrl:
     defaultZone: http://netflix-eureka-naming-server:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.int[5000,6000]}
    preferIpAddress: true
    #hostname: localhost #ipaddress of this host 
    #secure-port-enabled: false
    #non-secure-port-enabled: true
    #secure-port: ${server.port}
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include:
        - "*" #disabling security to enable actuator to call actuator/refresh url

server:
  port: 8089



