spring:
   rabbitmq:
    host: rabbitmq
   mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyatsharebazar
    password: sharebazar@123
    properties.mail.smtp:
       auth: true
       starttls.enable: true
   # in docker environment if you don't ignore these network intefaces you won't be able 
   #to hit Eureka ---> your service
   cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo
#========= RabbitMQ configuration ============
  

#============== Eureka client service registration
eureka:
  client:
    serviceUrl:
     defaultZone: http://netflix-eureka-naming-server:8761/eureka/
    instance:
     instance-id: ${spring.application.name}:${random.int[5000,6000]}
     prefer-ip-address: true
    #hostname: localhost #ipaddress of this host 
    #secure-port-enabled: false
    #non-secure-port-enabled: true
    #secure-port: ${server.port}
management:
  endpoints:
    web:
      exposure:
        include:
        - "*" #disabling security to enalbe actuator to call actuator/refresh url

server:
  port: 8089


