spring:
 rabbitmq:
   host: rabbitmq
   username: guest
   password: guest

 datasource:
   url: jdbc:mysql://mysql:3306/user_db
   username: root
   password: password
 jpa:
   hibernate:
     ddl-auto: update
   properties: 
     hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
   show-sql: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false 
#server.port=${random.int[9051,9080]}
#============== Eureka client service registration
eureka:
  client:
    serviceUrl:
     defaultZone: http://netflix_eureka_naming_server:8761/eureka/
    instance:
     instance-id: ${spring.application.name}:${random.int[5000,6000]}
     prefer-ip-address: true
