spring:
 rabbitmq:
   host: localhost
   username: guest
   password: guest

 datasource:
   url: jdbc:mysql://localhost:3306/test
   username: root
   password: root
 jpa:
   hibernate:
     ddl-auto: update
   properties: 
     hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
   show-sql: true
 zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}  
 sleuth:
   sampler:
      probability: 1

server:
  port: 9090
  error:
    whitelabel:
      enabled: false 
#server.port=${random.int[9051,9080]}
#============== Eureka client service registration
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
    instance:
     instance-id: ${spring.application.name}:${random.int[5000,6000]}
     prefer-ip-address: true