spring:
 rabbitmq:
   host: rabbitmq
   username: guest
   password: guest

 datasource:
   url: jdbc:mysql://mysql:3306/user_db
   username: root
   password: password
 jpa:
   hibernate:
     ddl-auto: update
   properties: 
     hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
   show-sql: true
   # ignoring network intefaces in docker world to make sure that eureka is working
 cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo
 zipkin:
   enabled: true
   base-url: http://zipkin:9411
   service:
     name: ${spring.application.name}
 sleuth:
    sampler:
      probability: 1
server:
  port: 8080
  error:
    whitelabel:
      enabled: false 
#server.port=${random.int[9051,9080]}
#============== Eureka client service registration
eureka:
  client:
    serviceUrl:
     defaultZone: http://netflix-eureka-naming-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int[5000,6000]}
    preferIpAddress: true
